#!/usr/bin/env bash

deck=$1

if [[ -z $ANKI_COLLECTION_PATH ]]; then
    ANKI_COLLECTION_PATH="$HOME/.local/share/Anki2/User 1/collection.anki2"
fi

learning_query="SELECT COUNT(*) FROM cards c JOIN decks d ON c.did = d.id WHERE d.name = '$deck' COLLATE NOCASE AND c.ivl != 0;"
all_query="SELECT COUNT(*) FROM cards c JOIN decks d ON c.did = d.id WHERE d.name = '$deck' COLLATE NOCASE;"

# TODO: Is there really no other way to work around the exclusive lock that
# Anki or AnkiConnect seems to hold than copying the whole database?
tmp_db=/tmp/anki.sqlite3
cp "$ANKI_COLLECTION_PATH" $tmp_db
learning_count=$(sqlite3 -readonly $tmp_db "$learning_query")
all_count=$(sqlite3 -readonly $tmp_db "$all_query")
rm $tmp_db

echo $learning_count/$all_count
